### ISSUE TITLE
Typescript - withHandler type error

### ISSUE THREAD

**Issue by alexandermckay** [TrueFit/bach-recompose#6]
I am getting a typescript warning that appears to be an error

```
Property 'X' does not exist on type 'Props | undefined'
```

I have recreated an [example of the issue](https://codesandbox.io/s/truefit-counter-example-kfl3s?file=/src/app/index.tsx). Look specifically at the `withHandlers` object

**Comment by jgretz** [comment]
The type definition wasnt working as I expected (obviously :))

I have updated the type definitions to behave as they should. Please update to version 2.0.3 (published 30 seconds ago)

**Comment by jgretz** [comment]
Thanks for the clear example btw - made it easy to track down
