### ISSUE TITLE
withProps is not correct inferring type

### ISSUE THREAD

**Issue by alexandermckay** [TrueFit/bach-recompose#7]
For each method on the object passed to `withProps`, the prop argument should have its type correctly inferred rather than needing to be explicitly set for each method.

**Current behaviour**
```typescript
withProps<InfoProps>({
  getName: (props: InfoProps) => props.getName,
  getAge: (props: InfoProps) => props.getAge,
  getGender: (props) => props.getGender  // props implicitly has type 'any'
})
```

**Desired Behaviour**
```typescript
withProps<InfoProps>({
  getName: (props) => props.getName,
  getAge: (props) => props.getAge,
  getGender: (props) => props.getGender
})
```

Working example available [here](https://codesandbox.io/s/spring-shape-ujcpl?file=/src/App.tsx)

**Comment by jgretz** [comment]
Fixed typing in version 2.0.4

Thanks
